### ISSUE TITLE
regd:LAS model implementation in pytorch

### ISSUE THREAD

**Issue by harikrishnavydana** [XenderLiu/Listen-Attend-and-Spell-Pytorch#1]
can i get your email??

**Comment by XenderLiu** [comment]
Sure! I added it in description section.

**Comment by nvidiaman** [comment]
@Alexander-H-Liu Hello, thank you for the implementation. Could you check my issue https://github.com/Alexander-H-Liu/Listen-Attend-and-Spell-Pytorch/issues/12 ?
