### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by chenting0324** [XenderLiu/Listen-Attend-and-Spell-Pytorch#2]
Hello! I want to know how can I use the pretrained model to recognize an audio file,  Can you show an example?

**Comment by XenderLiu** [comment]
Hi!
Temporary, you may preprocess what ever you'd like to feed the model into MFCC-26 form
(please refer to 'create_mfcc ' in util/preprocess.py if you don't know how)
For more simplified and complete example, I'll get around with it once I have time.
Thank you!
